apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::128534335037:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5KD2GQ3V41FD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::128534335037:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-28T14:54:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "867"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 58fc7a95-994b-4aef-ac55-e61485bb90da
